import json
import os
import random
from dotenv import load_dotenv

load_dotenv()

# Listas de valores ficticios para enmascarar los datos
roles =[
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Software Engineer",
    "Software Architect",
    "Mobile Developer",
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Data Analyst",
    "Database Administrator",
    "Big Data Specialist",
    "DevOps Engineer",
    "Systems Administrator",
    "Network Administrator",
    "Cybersecurity Specialist",
    "Security Engineer",
    "Penetration Tester (Pentester)",
    "Security Analyst",
    "Security Architect",
    "Cloud Computing Specialist",
    "Cloud Solutions Architect",
    "Cloud Infrastructure Administrator",
    "Automation Engineer",
    "Integration Engineer",
    "API Developer",
    "QA Tester",
    "Automated Testing Engineer",
    "Technology Manager",
    "Scrum Master",
    "Product Owner",
    "IT Project Manager",
    "IT Business Analyst",
    "UX/UI Specialist",
    "User Experience Designer",
    "Game Developer",
    "Augmented Reality Engineer",
    "Virtual Reality Engineer",
    "Blockchain Engineer",
    "Smart Contracts Developer",
    "Server Administrator",
    "Virtualization Specialist",
    "Linux Administrator",
    "Windows Server Administrator",
    "Technical Support Engineer",
    "ITIL Specialist",
    "Technology Consultant",
    "Infrastructure Architect",
    "No-Code/Low-Code Developer",
    "Internet of Things (IoT) Specialist"
]

animals = [
    "Abeja",
    "Abejorro",
    "Águila",
    "Alce",
    "Almeja",
    "Anaconda",
    "Anguila",
    "Antílope",
    "Araña",
    "Ardilla",
    "Avestruz",
    "Avispa",
    "Babosa",
    "Ballena",
    "Bisonte",
    "Boa",
    "Búfalo",
    "Burro",
    "Caballo",
    "Cabra",
    "Caimán",
    "Calamar",
    "Camaleón",
    "Camello",
    "Canario",
    "Cangrejo",
    "Canguro",
    "Caracol",
    "Castor",
    "Cebra",
    "Cernícalo",
    "Cerdo",
    "Ciervo",
    "Cigüeña",
    "Cisne",
    "Cobra",
    "Cochinilla",
    "Cocodrilo",
    "Colibrí",
    "Comadreja",
    "Conejo",
    "Coral",
    "Cormorán",
    "Coyote",
    "Cucaracha",
    "Delfín",
    "Dromedario",
    "Elefante",
    "Erizo",
    "Escarabajo",
    "Escorpión",
    "Estrella de mar",
    "Flamenco",
    "Foca",
    "Gacela",
    "Gallina",
    "Gallo",
    "Gamba",
    "Gato",
    "Gaviota",
    "Gorila",
    "Grillo",
    "Guacamayo",
    "Guepardo",
    "Halcón",
    "Hamster",
    "Hiena",
    "Hipopótamo",
    "Hormiga",
    "Hurón",
    "Iguana",
    "Jabalí",
    "Jaguar",
    "Jirafa",
    "Koala",
    "Lagarto",
    "Langosta",
    "Lechuza",
    "Lémur",
    "León",
    "Leopardo",
    "Lobo",
    "Loro",
    "Luciérnaga",
    "Mamut",
    "Manatí",
    "Mapache",
    "Medusa",
    "Mofeta",
    "Mono",
    "Morsa",
    "Mosca",
    "Mosquito",
    "Murciélago",
    "Nutria",
    "Orangután",
    "Orca",
    "Oruga",
    "Oso",
    "Ostra",
    "Paloma",
    "Pantera",
    "Pato",
    "Pavo",
    "Perezoso",
    "Perro",
    "Pez payaso",
    "Pingüino"
]

animal_types = [
    "Mamífero",
    "Reptil",
    "Ave",
    "Pez",
    "Anfibio",
    "Insecto",
    "Arácnido",
    "Crustáceo",
    "Molusco",
    "Equinodermo",
    "Cnidario",
    "Gusano",
    "Miriápodo",
    "Marsupial",
    "Rumiantes",
    "Roedor",
    "Carnívoro",
    "Herbívoro",
    "Omnívoro",
    "Acuático"
]

actors = [
    "Tom Hanks",
    "Meryl Streep",
    "Leonardo DiCaprio",
    "Scarlett Johansson",
    "Brad Pitt",
    "Angelina Jolie",
    "Denzel Washington",
    "Robert De Niro",
    "Al Pacino",
    "Natalie Portman",
    "Morgan Freeman",
    "Cate Blanchett",
    "Johnny Depp",
    "Viola Davis",
    "Christian Bale",
    "Nicole Kidman",
    "Joaquin Phoenix",
    "Charlize Theron",
    "Hugh Jackman",
    "Emma Stone",
    "Samuel L. Jackson",
    "Julia Roberts",
    "Ryan Gosling",
    "Anne Hathaway",
    "Matt Damon",
    "Jennifer Lawrence",
    "Keanu Reeves",
    "Sandra Bullock",
    "Jake Gyllenhaal",
    "Emily Blunt",
    "Robert Downey Jr.",
    "Amy Adams",
    "Javier Bardem",
    "Salma Hayek",
    "Idris Elba",
    "Marion Cotillard",
    "Chris Hemsworth",
    "Tilda Swinton",
    "Adam Driver",
    "Jessica Chastain",
    "Benedict Cumberbatch",
    "Halle Berry",
    "Michael Fassbender",
    "Brie Larson",
    "Daniel Day-Lewis",
    "Timothée Chalamet",
    "Kate Winslet",
    "Eddie Redmayne",
    "Chris Evans",
    "Tom Hardy"
]

def truncate_description(description, length=50):
    if isinstance(description, str) and len(description) > length:
        return description[:length] + "..."
    return description

def mask_data(data):
    for item in data:
        item["project"] = random.choice(animals)
        item["industry"] = random.choice(animal_types)
        item["contact"] = random.choice(actors)
        item["roleName"] = random.choice(roles)

        if "description" in item:
            item["description"] = truncate_description(item["description"], 50)
    
    return data

def process_json(input_data):
    masked_data = mask_data(input_data)
    return masked_data
